# Generated by Django 4.1.7 on 2023-04-08 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_company_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vacancy',
            options={'verbose_name': 'Vacancy', 'verbose_name_plural': 'Vacancies'},
        ),
    ]
